docker install

diff --git a/scripts/install_docker b/scripts/install_docker
--- a/scripts/install_docker
+++ b/scripts/install_docker
@@ -5,7 +5,42 @@
 # Install Docker CE
 
 
+do_update () {
+	apt-get --assume-yes update
+}
+
+do_install_dependencies () {
+sudo apt-get --assume-yes install \
+     apt-transport-https \
+     ca-certificates \
+     curl \
+     gnupg2 \
+     software-properties-common
+}
+
+do_add_docker_GPG_keys () {
+curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
+}
+
+do_check_docker_fingerprint () {
+FINGERPRINT=0EBFCD88
+
+if [[ ! $(apt-key fingerprint $FINGERPRINT) ]] ; then
+	echo "docker gpg fingerprint $FINGERPRINT not found"
+	exit 1
+fi
+}
+
+do_get_stable_version() {
+sudo add-apt-repository \
+   "deb [arch=amd64] https://download.docker.com/linux/debian \
+   $(lsb_release -cs) \
+   stable"
+}
+
 do_install_docker_CE () {
+	sudo apt-get --assume-yes update
+	sudo apt-get --assume-yes install docker-ce
 
 }
 
